#!/bin/bash


function addGame() {
    read -rp "What is the name of the game?: " nameofgame;
    read -rp "Where is the executable for $nameofgame?: " locationofgame;
    read -rp "Would you like to save this game?: [y/n] " command;
    case $command in
        [Yy]* ) echo "Adding $nameofgame";
                newgame="$asgl_games/$nameofgame.sh"
                echo "$locationofgame" > "$newgame";
                chmod +x "$newgame";
                echo 'Game Added!';;
        [Nn]* ) echo "$nameofgame not added!";;
    esac
}

function launchGame() {
    read -rp "What game would you like to play?: " nameofgame;
    sh "$asgl_games/$nameofgame.sh";
}

function listGames() {
    echo 
    ls "$asgl_games" | awk -F. '{ print $1 }'
    echo 
}

function gethelp() {
    echo 
    echo a -------- add a game
    echo p -------- play a game
    echo l -------- listgames
    echo h -------- list of commands
    echo q -------- exit
    echo 
}


while :
do
    read -rp "Type a command (h for help): " answer
    case $answer in
        [Aa]* ) addGame ;;
        [Pp]* ) launchGame ;;
        [Ll]* ) listGames ;;
        [Hh]* ) gethelp ;;
        [Qq]* ) echo 'Exiting asgl. Goodbye.' && exit ;;
    esac
done
