#!/usr/bin/env bash

asgl_home="$HOME/.local/share/asgl"
asgl_games="$asgl_home/games"

[ ! -d "$asgl_home" ] && echo "Creating asgl home directory." && mkdir -pv "$asgl_home"
[ ! -d "$asgl_games" ] && echo "Creating asgl game directory." && mkdir -pv "$asgl_games"

add() {
    clear
    read -rp "What is the name of the game?: " nameofgame
    read -rp "Where is the executable for $nameofgame?: " locationofgame
    read -rp "Would you like to save this game?: [y/n] " command
    case $command in
        [Yy]*)
            echo "Adding $nameofgame"
            newgame="$asgl_games/$nameofgame.sh"
            echo "$locationofgame" > "$newgame"
            chmod +x "$newgame"
            echo 'Game Added!'
            ;;
        [Nn]*) echo "$nameofgame not added!";;
        *) echo "Not a valid option.";;
    esac
    menu
}

remove() {
    clear
    read -rp "What game would you like to remove?: " nameofgame
    read -rp "Would you like to remove $nameofgame? [Y/n}: " command
    case $command in
        [Y/y]*)
            echo "Removing $nameofgame"
            echo "$nameofgame removed"
            ;;
        [N/n]*) echo "$nameofgame not removed";;
        *) echo "Not a valid option";;
    esac
    menu
}

play() {
    clear
    read -rp "What game would you like to play?: " nameofgame
    sh "$asgl_games/$nameofgame.sh"
    menu
}

list() {
    clear
    echo -e "
$(ls "$asgl_games" | awk -F. '{ print $1 }')
    "
    menu
}

help() {
    clear
    echo -e "
a/A -------- Add a game.
r/R -------- Remove a game.
p/P -------- Play a game.
l/L -------- List games.
h/H -------- List of commands.
q/Q -------- Exit.
    " 
    menu
}

menu() {
    read -rp "Type a command (h for help): " answer
        case $answer in
            [Aa]*) add;;
	    [Rr]*) remove;;
            [Pp]*) play;;
            [Ll]*) list;;
            [Hh]*) help;;
            [Qq]*) echo "Exiting asgl. Goodbye." && exit 0;;
            *) echo "Not a valid option, exiting." && exit 1;;
        esac
}

menu
